name          'philandstuff-elasticsearch'
version       '0.0.1'
source        'UNKNOWN'
author        'philandstuff'
license       'MIT'
summary       'UNKNOWN'
description   'UNKNOWN'
project_page  'UNKNOWN'

dependency 'puppetlabs/stdlib', '>= 3.0.0'
